name: Node CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest, windows-latest]
                node-version:
                    - 14.x
                    - 12.x
                    - 10.x
        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: build
              run: |
                  yarn install
                  yarn pack
              env:
                  CI: true
